[Firebase] URLSessionService 리팩토링
boostcampwm-2022/iOS09-burstcamp pull request #109
Opened 2022-11-24 14:41 UTC by NEULiee

## 관련 이슈
- #58 

## 내용
- URLSession 리팩토링하고 user save, update, fetch 쿼리 추가했습니다.

## 리뷰어가 확인할 사항
 

## 기타

2022-11-24 15:49 UTC, Kim-Coding requested changes

2022-11-24 15:49 UTC, Kim-Coding commented on burstcamp/burstcamp/Service/LogInManager.swift
> +            .mapError { _ in NetworkError.responseDeoingError }
P2: Decoding입니다

2022-11-24 15:50 UTC, NEULiee commented on burstcamp/burstcamp/Service/LogInManager.swift
> +            .mapError { _ in NetworkError.responseDeoingError }
세상에나

2022-11-25 01:48 UTC, never-better requested changes

2022-11-25 01:48 UTC, never-better commented on burstcamp/burstcamp/Util/Constant/NetworkError.swift
> +    var errorDescription : String {
세세한 예외 처리 좋습니다!

2022-11-25 02:23 UTC, NEULiee commented on burstcamp/burstcamp/Util/Constant/NetworkError.swift
> +    case responseDeoingError
수정헀습니다!

2022-11-25 02:23 UTC, NEULiee commented on burstcamp/burstcamp/Service/FireStoreService.swift
> +            httpHeaders: [(key: "Content-Type", value: "text/plain")],
수정헀습니다~!

2022-11-25 04:20 UTC, never-better approved these changes

2022-11-25 04:21 UTC, Kim-Coding approved these changes

2022-11-25 04:22 UTC, merged