feat: 자동로그인 구현, 멤버 여부에 따른 로직, 가입 되어있는지에 따른 로직 추가
boostcampwm-2022/iOS09-burstcamp pull request #118
Opened 2022-11-27 07:40 UTC by Kim-Coding

## 관련 이슈
 
close #7 

## 내용
 
- 기관 인증 후 FirebaseStore의 fetchUser 함수로 회원가입 여부 판단
- 회원가입 필요하면 userUUID와 nickname을 파라미터로 넣고 Domain선택 창으로 이동
- 회원가입이 되어있으면 TabBar로 이동
- Need: 에러처리를 더 명확히 할 필요가 있음

## 리뷰어가 확인할 사항
 

## 기타

2022-11-27 07:51 UTC, NEULiee approved these changes
고생하셨습니다!

금요일에 논의했던 것은 어떻게 되었는지 여쭤봐두될까요?

2022-11-27 07:51 UTC, NEULiee commented on burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
> +                signupDate: "", // TODO: 노션DB에는 Date로, User모델에는 String으로. 확인 필요
FireStore 모델을 모두 변경중에 있었습니다

2022-11-27 07:51 UTC, NEULiee commented on burstcamp/burstcamp/Coordinator/AuthCoordinator.swift
> +    func moveToDomainScreen(userUUID: String, nickname: String)
질문

유저의 ProfileURL은 받아오지 않나요?

2022-11-27 07:51 UTC, NEULiee commented on burstcamp/burstcamp/Service/LogInManager.swift
>          requestGithubAccessToken(code: code)
P3

로직이 많이 길어지는 것 같은데 함수로 분리하면 깔끔할 것 같습니다!

2022-11-27 08:00 UTC, Kim-Coding commented on burstcamp/burstcamp/Coordinator/AuthCoordinator.swift
> +    func moveToDomainScreen(userUUID: String, nickname: String)
추가했습니다

https://github.com/유저닉네임.png

2022-11-27 08:00 UTC, Kim-Coding commented on burstcamp/burstcamp/Scene/Auth/SignUp/Blog/SignUpBlogViewController.swift
> +                signupDate: "", // TODO: 노션DB에는 Date로, User모델에는 String으로. 확인 필요
확인했습니다

2022-11-28 09:54 UTC, never-better requested changes

2022-11-28 09:54 UTC, never-better commented on burstcamp/burstcamp/Scene/Auth/SignUp/SignUpViewModel.swift
> +    init(userUUID: String, nickname: String) {
Q: userUUID랑 nickname만 초기값이 필요한 이유가 있나요? 다른 프로퍼티 처럼 초기값이 있는 상태에서 시작하는 거랑 무슨 차이가 있는 건가요??

2022-11-28 09:54 UTC, never-better commented on burstcamp/burstcamp/Service/LogInManager.swift
>      static let shared = LogInManager()
p4: 로그인 매니저가 로그인, 회원가입, 마이페이지에서 쓰이는 것 같은데, 싱글톤 말고 주입해주는게 좋지 않을까? 하는 생각입니다.

2022-11-28 10:57 UTC, Kim-Coding commented on burstcamp/burstcamp/Scene/Auth/SignUp/SignUpViewModel.swift
> +    init(userUUID: String, nickname: String) {
로그인 매니저에서 화면 전환 이벤트를 보내고 LogInViewController를 거쳐 AuthCoordinator에서 viewModel을 생성하고 domainViewController를 생성하는데 domain, camperID, blog처럼 viewmodel에서 관리하면 좋겠다고 생각해서 생성할 때 넣어주려 했습니다

2022-11-28 11:09 UTC, Kim-Coding commented on burstcamp/burstcamp/Service/LogInManager.swift
>      static let shared = LogInManager()
loginViewModel과 SceneDelegate에서 사용하고 있습니다

2022-11-28 11:13 UTC, Kim-Coding commented on burstcamp/burstcamp/Service/LogInManager.swift
>          requestGithubAccessToken(code: code)
분리했습니다

2022-11-28 11:14 UTC, never-better approved these changes
수고하셨습니다 👍

2022-11-28 11:14 UTC, merged