feat: camperID 3자리 맞추기
boostcampwm-2022/iOS09-burstcamp pull request #121
Opened 2022-11-28 12:21 UTC by Kim-Coding

## 관련 이슈
 
close #13 

## 내용
 
- camperID가 3자리 채워졌을때만 버튼 활성화
<img src = "https://user-images.githubusercontent.com/54696445/204275859-7369c5d3-3058-441d-bc37-71c269e2f741.png" width="324">

<img src = "https://user-images.githubusercontent.com/54696445/204275886-03a43052-8a70-4025-b5b5-a63f3f928f1d.png" width="324">

## 리뷰어가 확인할 사항
 

## 기타

2022-11-28 12:36 UTC, never-better requested changes

2022-11-28 12:36 UTC, never-better commented on burstcamp/burstcamp/Util/Extension/UI/UIView+addSubViews.swift
> +    func paddingView() -> UIView {
p2: extension에 함수를 정의하는 거라면 View를 리턴하는 것보다는 self에 속성을 적용해주는게 좋은 것 같습니다.
```swift
extension UITextField {
  func addHorizontalPadding() {
    let paddingView = UIView(frame: CGRect(x: 0, y: 0, width: 10, height: self.frame.height))
    self.leftView = paddingView
    self.rightView = paddingView
    self.leftViewMode = ViewMode.always
  }
}
```
이렇게 작성하면 어떨까요??
+TextField에만 적용되는거라면 굳이 UIView extension 에 정의할 필요가 없는 것 같습니다.

2022-11-28 12:36 UTC, never-better commented on burstcamp/burstcamp/Scene/Auth/SignUp/SignUpViewModel.swift
> +    @Published var camperID: String = ""
Q: @Published를 쓴 이유를 설명해주실 수 있나요?? (면접이라 생각하고 대답해주시면 감사하겠습니다!)

2022-11-28 12:38 UTC, Kim-Coding commented on burstcamp/burstcamp/Util/Extension/UI/UIView+addSubViews.swift
> +    func paddingView() -> UIView {
수정했습니다

2022-11-28 12:42 UTC, never-better commented on burstcamp/burstcamp/Util/Extension/UI/UIView+addSubViews.swift
> +    func paddingView() -> UIView {
지금 생각났는데 DefaultMultiLineLabel 클래스처럼 UITextField를 상속받는 클래스를 만드는 게 더 편하고 통일성 있어보입니다.

2022-11-28 12:52 UTC, Kim-Coding commented on burstcamp/burstcamp/Scene/Auth/SignUp/SignUpViewModel.swift
> +    @Published var camperID: String = ""
idTextField가 변경됨에 따라 함수가 호출되어 camperID가 변경되는데 그 함수의 완료 순간을 캐치하여
camperID의 길이를 체크하고 그 값에 따라  isValidateCamperID의 값을 변경합니다
isValidateCamperID도 값의 변경의 따라 이벤트를 방출하고 camperIDViewController에서 이벤트를 캐치하여 
nextButton의 속성값을 바꾸는 작업을 비동기적으로 처리할 수 있어서 사용했습니다

2022-11-28 12:56 UTC, never-better commented on burstcamp/burstcamp/Util/Extension/UI/UITextField+Padding.swift
> +extension UITextField {
p5: 필요없으면 지워줘도 될 것 같습니다

2022-11-28 12:56 UTC, never-better approved these changes
수고하셨습니다 👍

2022-11-28 13:00 UTC, Kim-Coding commented on burstcamp/burstcamp/Util/Extension/UI/UITextField+Padding.swift
> +extension UITextField {
수정했습니다

2022-11-28 13:37 UTC, NEULiee commented on burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewController.swift
>              action: #selector(nextButtonTouchUpInside(_:)),
P4

addTarget을 publisher로 바꾸는 것은 어떨까요?

2022-11-29 02:05 UTC, sseungmn approved these changes

2022-11-29 06:18 UTC, Kim-Coding commented on burstcamp/burstcamp/Scene/Auth/SignUp/CamperID/SignUpCamperIDViewController.swift
>              action: #selector(nextButtonTouchUpInside(_:)),
수정했습니다

2022-11-29 06:18 UTC, merged

2022-11-29 06:19 UTC, NEULiee approved these changes