Rss Feed 업데이트시 Feed 모델 수정
boostcampwm-2022/iOS09-burstcamp pull request #257
Opened 2022-12-26 16:09 UTC by NEULiee

## 관련 이슈
- #253 

## 내용
- scrapCount 0으로 설정
- thumbnailURL 이 thumbnail로 되어있던데 잘 사용하고 계신 것 같아서 피그마를 고치던지 FeedDB를 고치면 될 것 같습니다.
- feed 저장하는 것만 바꿔서 다른 기능이 잘 안될 것 같아요?

## 리뷰어가 확인할 사항
 

## 기타

2022-12-27 01:01 UTC, never-better requested changes

2022-12-27 01:01 UTC, never-better commented on Firebase-Functions/functions/service/firestoreManager.js
> +		writerProfileImageURL: writer['profileImageURL'],
p2: ProfileImage에도 URL이 붙어있으니까 다 URL 붙이는 걸로 통일하시면 좋을 것 같습니다.

2022-12-28 13:41 UTC, sseungmn approved these changes
LGTM

2022-12-30 05:40 UTC, Kim-Coding approved these changes

2023-01-02 04:00 UTC, never-better approved these changes

2023-01-02 04:00 UTC, merged